project:
  type: website
  output-dir: docs
#  resources: 
#      - materials

website:
  page-navigation: true
  title: "DATA/MATH 306"
  site-url: "https://mcconvil.github.io/data306f25"
  search: 
    type: overlay
  navbar:
    background: "#283618" 
    search: true
    style: "docked"
  # navbar:
  #   left:
  #   - text: "Homepage"
  #     icon: fa-home
  #     href: index.qmd
  #   - text: "Slides (First Half)"
  #     icon: fa-chart-area
  #     menu: 
  #       - text: "Week 1 Wed"
  #         icon: fa-file
  #         href: stat100_wk01wed.qmd

format:
  html:
    theme: yeti
    css: ["styles.css", "more.css"]
    toc: true